# Generated by Django 5.1.3 on 2024-12-04 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('poster_path', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='streaming.movie'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.movie'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_movies',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='streaming.movie'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='streaming.series'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_series',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='streaming.series'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='series',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.series'),
        ),
    ]
